trap:
  schematic: "trap.schem"
  display_name: "§6Трапка"
  description: "§7Используйте, чтобы установить ловушку!"
  type: "NETHERITE_SCRAP"
  cooldown: 20
  duration: 15
  messages:
    already_nearby: "Рядом уже установлена активная ловушка!"
    cooldown_message: "Подождите {time} секунд перед следующим использованием." # {time} - Это время в секундах, если не хотите его использовать, просто уберите.
    trap_failed: "Не удалось загрузить ловушку!"
  sound:
    type: "BLOCK_ANVIL_PLACE" # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html - Все типы звуков в игре.
    volume: 10.0f # Громкость звука.
    pitch: 1.0f # Тон звука.


plate:
  display_name: "§6Пласт"
  description: "§7Используйте, чтобы установить пласт!"
  type: "NETHERITE_SCRAP"
  cooldown: 20
  duration: 5
  messages:
    already_nearby: "Рядом уже установлен активный пласт!"
    cooldown_message: "Подождите {time} секунд перед следующим использованием." # {time} - Это время в секундах, если не хотите его использовать, просто уберите.
    placement_failed: "Не удалось загрузить пласт!"
  forward_schematic: "plate_forward.schem" # Значение yaw от -22.5 до 22.5(Значение pitch в этом случае неважно)
  forward_left_schematic: "plate_forward_left.schem" # Значение yaw от 22.5 до 67.5(Значение pitch в этом случае неважно)
  forward_right_schematic: "plate_forward_right.schem" # Значение yaw от -67.5 до -22.5(Значение pitch в этом случае неважно)
  backward_schematic: "plate_backward.schem" # Значение yaw от 157.5 до 180 ИЛИ от -157.5 до -180(Значение pitch в этом случае неважно)
  backward_left_schematic: "plate_backward_left.schem" # Значение yaw от 112.5 до 157.5(Значение pitch в этом случае неважно)
  backward_right_schematic: "plate_backward_right.schem" # Значение yaw от -112.5 до -157.5(Значение pitch в этом случае неважно)
  left_schematic: "plate_left.schem" # Значение yaw от 67.5 до 112.5(Значение pitch в этом случае неважно)
  right_schematic: "plate_right.schem" # Значение yaw от -67.5 до -112.5(Значение pitch в этом случае неважно)
  up_schematic: "plate_up.schem" # Значение pitch от -45 до -90(Значение yaw в этом случае неважно)
  down_schematic: "plate.schem" # Значение pitch от 45 до 90(Значение yaw в этом случае неважно)
  sound:
    type: "BLOCK_ANVIL_PLACE" # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html - Все типы звуков в игре.
    volume: 10.0f # Громкость звука.
    pitch: 1.0f # Тон звука.

reveal_item:
  type: SUGAR
  display_name: "§eЯвная пыль"
  description: "§7Снимает невидимость с игроков и даёт им эффект свечения."
  cooldown: 5
  radius: 10
  glow_duration: 5
  particle_type: CLOUD
  sound:
    type: "ENTITY_EXPERIENCE_ORB_PICKUP"
    volume: 1.0f
    pitch: 1.0f

disorient_item:
  display_name: "§dДезориентация"
  type: "ENDER_EYE"
  description:
    - "§7Используйте, чтобы наложить"
    - "§7негативные эффекты на игроков поблизости."
  cooldown: 10
  effect_duration: 5
  radius: 10
  sound:
    type: "ENTITY_WITHER_AMBIENT"
    volume: 1.0f
    pitch: 1.0f
  particle_type: "SMOKE_LARGE"

