name: VioTrap
version: '1.6'
main: org.migrate1337.viotrap.VioTrap
api-version: '1.16'
softdepend:
  - WorldEdit
  - WorldGuard
  - CombatLogX
  - PvPManager
commands:
  viotrap:
  createskin:
  applyskin: